<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EDIOI3Q" failures="1" tests="9" name="RetryMultipleFailedTestCases" time="80.351" errors="0" timestamp="2025-03-18T18:08:35 IST">
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="1.181">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="0.843">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="0.798">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="0.754">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="loginErrorValidation" time="0.89">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Incorrect email password.&amp;gt; but was:&amp;lt;Incorrect email or password.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Incorrect email password.> but was:<Incorrect email or password.>
at SeleniumFramework.Test.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="SeleniumFramework.Test.ErrorValidationTest" name="productErrorValidation" time="7.111"/>
  <testcase classname="SeleniumFramework.Test.CutomiseEndToEndTest" name="submitOrder" time="8.633"/>
  <testcase classname="SeleniumFramework.Test.CutomiseEndToEndTest" name="submitOrder" time="8.76"/>
  <testcase classname="SeleniumFramework.Test.CutomiseEndToEndTest" name="orderHistory" time="1.047"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
