<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-18T14:55:30 IST" name="Default suite" finished-at="2025-04-18T14:56:14 IST" duration-ms="44238">
    <groups>
      <group name="Purchase">
        <method signature="CutomiseEndToEndTest.submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" name="submitOrder" class="SeleniumFramework.Test.CutomiseEndToEndTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-04-18T14:55:30 IST" name="Default test" finished-at="2025-04-18T14:56:14 IST" duration-ms="44238">
      <class name="SeleniumFramework.Test.CutomiseEndToEndTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:55:31 IST" name="launchApp" finished-at="2025-04-18T14:55:48 IST" duration-ms="16731" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:55:48 IST" name="submitOrder" data-provider="getData" finished-at="2025-04-18T14:55:57 IST" duration-ms="9480" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Ritu@123, product=IPHONE 13 PRO, email=ritu@vln.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at SeleniumFramework.Test.CutomiseEndToEndTest.submitOrder(CutomiseEndToEndTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:55:57 IST" name="closebrowser" finished-at="2025-04-18T14:55:58 IST" duration-ms="735" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:55:58 IST" name="launchApp" finished-at="2025-04-18T14:56:04 IST" duration-ms="6380" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:56:04 IST" name="submitOrder" data-provider="getData" finished-at="2025-04-18T14:56:14 IST" duration-ms="9627" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Abc@123, product=ADIDAS ORIGINAL, email=Abc@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="closebrowser()[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:56:14 IST" name="closebrowser" finished-at="2025-04-18T14:56:14 IST" duration-ms="414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrowser -->
        <test-method signature="orderHistory()[pri:0, instance:SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]" started-at="2025-04-18T14:56:14 IST" name="orderHistory" finished-at="2025-04-18T14:56:14 IST" depends-on-methods="SeleniumFramework.Test.CutomiseEndToEndTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumFramework.Test.CutomiseEndToEndTest.orderHistory() on instance SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe depends on not successfully finished methods 
[SeleniumFramework.Test.CutomiseEndToEndTest.submitOrder() on instance SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumFramework.Test.CutomiseEndToEndTest.orderHistory() on instance SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe depends on not successfully finished methods 
[SeleniumFramework.Test.CutomiseEndToEndTest.submitOrder() on instance SeleniumFramework.Test.CutomiseEndToEndTest@4a003cbe]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
      </class> <!-- SeleniumFramework.Test.CutomiseEndToEndTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
